export const SHIPROCKET_STATUS_MAP={
    "NEW": "CREATED",
    "AWB GENERATED": "AWB_ASSIGNED",
    "OUT FOR PICKUP": "PICKUP_SCHEDULED",
    "PICKED UP": "PICKED_UP",
    "IN TRANSIT": "IN_TRANSIT",
    "OUT FOR DELIVERY": "OUT_FOR_DELIVERY",
    "DELIVERED": "DELIVERED",
    "RTO INITIATED": "RTO_INITIATED",
    "RTO DELIVERED": "RTO_DELIVERED",
    "CANCELLED": "CANCELLED",
};
